/* joe/autoconf.h.  Generated by CMake from cmake/autoconf.h.cmake.
 * This replaces the header autoconf generates from joe/autoconf.h.in. */

#ifndef _JOE_AUTOCONF_H
#define _JOE_AUTOCONF_H 1

/* Package information */
#define PACKAGE "@PROJECT_NAME@"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_NAME "@PROJECT_NAME@"
#define PACKAGE_STRING "@PROJECT_NAME@ @PROJECT_VERSION@"
#define PACKAGE_TARNAME "@PROJECT_NAME@"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define VERSION "@PROJECT_VERSION@"

/* Compiler characteristics */
#define PROTOTYPES 1
#define __PROTOTYPES 1
#define STDC_HEADERS 1
#define RETSIGTYPE void

/* Check to see if we can use strict prototypes */
#ifndef PARAMS
#  ifdef PROTOTYPES
#    define PARAMS(protos) protos
#  else
#    define PARAMS(protos) ()
#  endif
#endif

/* Header files */
#cmakedefine HAVE_CURSES_H 1
#cmakedefine HAVE_DIRENT_H 1
#cmakedefine HAVE_ERRNO_H 1
#cmakedefine HAVE_FCNTL_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_LIBUTIL_H 1
#cmakedefine HAVE_LIMITS_H 1
#cmakedefine HAVE_LOCALE_H 1
#cmakedefine HAVE_MEMORY_H 1
#cmakedefine HAVE_NDIR_H 1
#cmakedefine HAVE_PATHS_H 1
#cmakedefine HAVE_PTY_H 1
#cmakedefine HAVE_PWD_H 1
#cmakedefine HAVE_SELINUX_CONTEXT_H 1
#cmakedefine HAVE_SELINUX_SELINUX_H 1
#cmakedefine HAVE_SGTTY_H 1
#cmakedefine HAVE_SIGNAL_H 1
#cmakedefine HAVE_STDDEF_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_STDLIB_H 1
#cmakedefine HAVE_STRINGS_H 1
#cmakedefine HAVE_STRING_H 1
#cmakedefine HAVE_SYS_DIRENT_H 1
#cmakedefine HAVE_SYS_DIR_H 1
#cmakedefine HAVE_SYS_IOCTL_H 1
#cmakedefine HAVE_SYS_NDIR_H 1
#cmakedefine HAVE_SYS_PARAM_H 1
#cmakedefine HAVE_SYS_STAT_H 1
#cmakedefine HAVE_SYS_TERMIO_H 1
#cmakedefine HAVE_SYS_TIME_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_UTIME_H 1
#cmakedefine HAVE_SYS_WAIT_H 1
#cmakedefine HAVE_TERMIO_H 1
#cmakedefine HAVE_TERM_H 1
#cmakedefine HAVE_TIME_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_UTIME_H 1
#cmakedefine HAVE_UTMP_H 1
#cmakedefine HAVE_VFORK_H 1

/* Terminal interface */
#cmakedefine HAVE_POSIX_TERMIOS 1
#cmakedefine HAVE_SYSV_TERMIO 1
#cmakedefine GWINSZ_IN_SYS_IOCTL 1
#cmakedefine TERMINFO 1

/* SELinux */
#cmakedefine HAVE_SELINUX 1

/* Types and sizes */
#cmakedefine HAVE_LONG_LONG 1
#cmakedefine HAVE_SIGHANDLER_T 1
#define SIZEOF_CHAR @SIZEOF_CHAR@
#define SIZEOF_SHORT @SIZEOF_SHORT@
#define SIZEOF_INT @SIZEOF_INT@
#define SIZEOF_LONG @SIZEOF_LONG@
#define SIZEOF_LONG_LONG @SIZEOF_LONG_LONG@
#define SIZEOF_VOID_P @SIZEOF_VOID_P@
#define SIZEOF_OFF_T @SIZEOF_OFF_T@
#cmakedefine ssize_t @ssize_t@

/* Library functions */
#cmakedefine HAVE_ALARM 1
#cmakedefine HAVE_FORK 1
#cmakedefine HAVE_WORKING_FORK 1
#cmakedefine HAVE_VFORK 1
#cmakedefine HAVE_WORKING_VFORK 1
#cmakedefine vfork @vfork@
#cmakedefine HAVE_GETCWD 1
#cmakedefine HAVE_GETWD 1
#cmakedefine HAVE_ISBLANK 1
#cmakedefine HAVE_WORKING_ISBLANK 1
#cmakedefine HAVE_LOGIN_TTY 1
#cmakedefine HAVE_MKDIR 1
#cmakedefine HAVE_MKSTEMP 1
#cmakedefine HAVE_OPENPTY 1
#cmakedefine HAVE_PUTENV 1
#cmakedefine HAVE_SETITIMER 1
#cmakedefine HAVE_SETLOCALE 1
#cmakedefine HAVE_SETPGID 1
#cmakedefine HAVE_SIGACTION 1
#cmakedefine HAVE_SIGINTERRUPT 1
#cmakedefine HAVE_SIGPROCMASK 1
#cmakedefine HAVE_SIGVEC 1
#cmakedefine HAVE_SNPRINTF 1
#cmakedefine HAVE_STRCHR 1
#cmakedefine HAVE_STRDUP 1
#cmakedefine HAVE_UTIME 1
#cmakedefine LSTAT_FOLLOWS_SLASHED_SYMLINK 1
#cmakedefine SETPGRP_VOID 1
#cmakedefine NEED_TO_REINSTALL_SIGNAL 1

/* Math functions */
#cmakedefine HAVE_SIN 1
#cmakedefine HAVE_COS 1
#cmakedefine HAVE_TAN 1
#cmakedefine HAVE_EXP 1
#cmakedefine HAVE_SQRT 1
#cmakedefine HAVE_CBRT 1
#cmakedefine HAVE_LOG 1
#cmakedefine HAVE_LOG10 1
#cmakedefine HAVE_ASIN 1
#cmakedefine HAVE_ACOS 1
#cmakedefine HAVE_ATAN 1
#cmakedefine HAVE_SINH 1
#cmakedefine HAVE_COSH 1
#cmakedefine HAVE_TANH 1
#cmakedefine HAVE_ASINH 1
#cmakedefine HAVE_ACOSH 1
#cmakedefine HAVE_ATANH 1
#cmakedefine HAVE_FLOOR 1
#cmakedefine HAVE_CEIL 1
#cmakedefine HAVE_FABS 1
#cmakedefine HAVE_ERF 1
#cmakedefine HAVE_ERFC 1
#cmakedefine HAVE_J0 1
#cmakedefine HAVE_J1 1
#cmakedefine HAVE_Y0 1
#cmakedefine HAVE_Y1 1
#cmakedefine HAVE_HYPOT 1

#endif /* _JOE_AUTOCONF_H */
